name: Delete merged/closed branch

on:
  pull_request:
    types: [closed]
    branches:
      - main
      
jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Delete branch
        run: |-
          git config --global user.email "arjun140702@gmail.com"
          git config --global user.name "Arjun"
          git push -d origin ${{ github.event.pull_request.head.ref }}
