name: Create a Pull Request

on:
  push:
    branches: [ dev ]
    
jobs:
#       - name: Update package.json
#         run: |-
#           npm ci
#           npm i -g json
#           json -I -f package.json -e "this.scripts.build=\"cd .next && npm install && npm run build\""
          
#           git config --global user.email "arjun140702@gmail.com"
#           git config --global user.name "Arjun"
#           git diff
#           git add .
#           git commit -m "refactor: Update build command"
#           git push -f origin backend 
  pull-request:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}    
    steps:
      - uses: actions/checkout@v2
     
      - name: Use Python 3  
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Create a Pull Request    
        run: |-
          cd .github
          pip install requests
          python3 pull-req.py
        continue-on-error: true
