name: Create a Pull Request

on:
  push:
    branches: [ backend, frontend ]
    
jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    if: ${{ github.ref == 'refs/heads/backend' }}
    env:
      TOKEN: ${{ secrets.TOKEN }}    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Update package.json
        run: |-
          npm ci
          npm i -g json
          json -I -f package.json -e "this.scripts.build=\"cd .next && npm install && npm run build\""
          
          git config --global user.email "arjun140702@gmail.com"
          git config --global user.name "Arjun"
          git diff
          git add .
          git commit -m "refactor: Update build command"
          git push -f origin backend
        
      - name: Use Python 3  
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: |-
          cd .github
          pip install requests
          python3 pull-req.py backend
            
  frontend:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/frontend' }}
    env:
      TOKEN: ${{ secrets.TOKEN }}    
    steps:
      - uses: actions/checkout@v2
     
      - name: Use Python 3  
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: |-
          cd .github
          pip install requests
          python3 pull-req.py frontend
